### ISSUE TITLE
Meta Package

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [magespecialist/m2-MSP_SecuritySuiteFull#1]
Hello,

Your extensions look real promising, now I only wonder why you created a module.xml in this meta package? Because composer supports meta packages which means it will only read the composer.json from this repository. So we don't need an extra magento 2 module. I can create a pull request if you want.

**Comment by GeoffreyDijkstra** [comment]
Side note: the composer.json doesn't need the "version" entry/number it will use the version number from github when connected to packagist :smile:

It makes life a little easier, because you don't need to change your version entry in composer.json every time you make a new release.

**Comment by phoenix128** [comment]
Hello @GeoffreyDijkstra ,
your comments make sense :) expecially the one about module.xml, it is not needed actually.
It was probably left there from the old module architecture.

We will really appreciate your contribution if you wish to create a pull request.

**Comment by phoenix128** [comment]
Thank you for your contrib ;)

**Comment by GeoffreyDijkstra** [comment]
Maybe I'm a little annoying now :smile: 
But why did you release a stable release as 0.1.3 because IMO that still is a develop release.

I guess you might now this but versions should be like: Major / Feature / Hotfix (and I hate the "v" prefix :grin:) and everything starting with 0.*  is a develop release "pre"-stable :stuck_out_tongue: 

But thx for the merge :wink:

**Comment by phoenix128** [comment]
@GeoffreyDijkstra ,
you are more than right. The wreng versioning model here is a very old story ;)
But thank you for your suggestions, we really appreciate. We will fix it ASAP.
